export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG'
export const CHANGE_CURRENT_INDEX = 'CHANGE_CURRENT_INDEX'
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST'
export const CHANGE_RULE = 'CHANGE_RULE'

export const CHANGE_LYRIC = 'CHANGE_LYRIC'
export const CHANGE_CURRENT_LYRIC_INDEX = 'CHANGE_CURRENT_LYRIC_INDEX'

export const CHANGE_COMMENT = 'CHANGE_COMMENT'

export const CHANGE_SIMILAR_SONG_LIST = 'CHANGE_SIMILAR_SONG_LIST'
