export const CHANGE_ARTIST_LIST = 'CHANGE_ARTIST_LIST'
export const CHANGE_ARTIST_SONG = 'CHANGE_ARTIST_SONG'
export const CHANGE_ARTIST_DESC = 'CHANGE_ARTIST_DESC'
export const CHANGE_ARTIST_ALBUM = 'CHANGE_ARTIST_ALBUM'
