export const CHANGE_DJ_CAT = 'CHANGE_DJ_CAT'
export const CHANGE_CURRENT_TYPE = 'CHANGE_CURRENT_TYPE'

export const CHANGE_CURRENT_RECOMMEND = "CHANGE_CURRENT_RECOMMEND"
export const CHANGE_CURRENT_HOT_DJ = "CHANGE_CURRENT_HOT_DJ"