export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'
export const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND'
export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM'

export const CHANGE_TOP_LIST = 'CHANGE_TOP_LIST'
export const CHANGE_NEW_LIST = 'CHANGE_NEW_LIST'
export const CHANGE_ORIGIN_LIST = 'CHANGE_ORIGIN_LIST'




